### ISSUE TITLE
Proposal: Add library-like public API

### ISSUE THREAD

**Issue by titusjaka** [rantav/go-archetype#10]
Hi @rantav 👋

First of all, thank you for the go-archetype ❤️. I love the approach you implemented.

We use go-archetype at @youla-dev as a CLI tool right now. But we would like to adopt it as a library and embed it in our own CLI tool. To make this happen we should make some minor changes in the code base of go-archetype. It won't affect the current public API but will make go-archetype more flexible.

What changes we would like to implement:

- [x] update the go version to at least 1.13. Preferable is 1.17. (#11)
- [x] simplify Github Actions, since go 1.13+ doesn't need `GOPATH` and other hacks. (#11)
- [x] remove some dependencies (e.g. replace `github.com/pkg/errors` with `errors`). (#12)
- [ ] change inner interfaces. For example, change the `transformer.Transform` function to this signature: `Transform(source fs.FS, destination string, transformations Transformations) error`. This will allow using embedded source code, not only local files.
- [x] add a new transformation — rename. This transformation will rename files. (#14)
- [x] Add support for multi-line shell scripts. (#15)
- [ ] refactor shell executor to make it testable (see https://blog.sergeyev.info/golang-shell-commands/)
- [x] refactor logger: get rid of the global logger, pass it as an argument instead. (#16)

I open this issue since you are the author and the core maintainer of the go-archetype. We at @youla-dev would like to make a contribution to this open-source project. But it could contradict your vision of the go-archetype.
Please, let me know if these suggestions are fine for you.

**Comment by rantav** [comment]
Hi @titusjaka thank you!
I think your suggestions make sense, as long as the CLI to the tool doesn't change then it's an easy call, improvements are welcome.

**Comment by titusjaka** [comment]
It's me again 🤓

I tried to change the internal interfaces, but I failed.

Here are the changes I wanted to do:
1. `transformer.Transform` -> `Transform(sourceFS fs.FS, sourcePath, destinationPath string, transformations Transformations) error`
2. `transformer.Read` -> `Read(transformationfile io.Reader) (*Transformations, error)`
3. `reader.ReadFile` -> `ReadFile(path string, sourceFile fs.File, info os.FileInfo, sourceDir string, isIgnored func(string) bool) (isDir, ignored bool, file types.File, err error)`
4. `generator.Generate` -> `generator.Generate(transformations io.Reader, sourceFS fs.FS, sourcePath, destinationPath string, inputVars []string) error `

The idea was to decouple from the physical file system. So that you can pass the file with transformations and source files from anywhere (for example, over the network, embedded code, or from a zip archive).

But it turned out that this approach has several drawbacks:
- the virtual file system does not know anything about file permissions. For example, files from the `embed` package always have permissions 0444, and directories - 0555.
- there are difficulties with determining the relative path (used for exclude).

As a result, I came to the conclusion that these changes don't make sense. They create more problems than they solve

Maybe in the future I will have a new idea of how to implement that and try again.


P.S.: As for the rest of the points from my original post, I plan to deal with them in the near future.
